# Generated by Django 4.2.4 on 2023-10-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_sec', models.TextField()),
                ('self_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
