# Generated by Django 4.2.4 on 2023-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_links', models.CharField(max_length=200)),
                ('s_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
